theme: jekyll-theme-hacker
title: Sometimes a little discomfort in the beginning can save a whole lot of pain down the road.
description: Some of us get dipped in flat some in satin some in gloss. But every once in a while you find someone who's iridescent. And when you do nothing will ever compare.