name: yhgao
author: gaoooyh
url: gaoooyh.github.io
baseurl: https://www.baidu.com
resume_site: this is a resume site.
description: this is a description.
github_username: gaoooyh
github: https://www.github.com/gaoooyh
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : 
    owner : 
    admin : 
